# Generated by Django 5.0.6 on 2024-06-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='loan_approve',
            field=models.BooleanField(default=False),
        ),
    ]
